### PR TITLE
Feature/add tracking categories

### PR DESCRIPTION
**Pull request by joidegn**

### CODE REVIEW

**Comment by freakboy3742** [comment]
This appears to be identical to #194... Since this PR is on a branch, I'm going to preserve this one, and close the other. However, my comments from that branch also apply here.

**Comment by joidegn** [comment]
Hey, sorry about the delay in updating this. I had missed your messages above. Updated the naming and got up to speed with some of the additional code quality checks we are now doing

**Comment by joidegn** [comment]
Super happy that there is activity on this project btw!

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Apologies for the long delay in reviewing this; it appears that the PR has drifted out of sync with the main branch. Are you able to update it so it can be reviewed?

**Comment by freakboy3742** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
