### PR TITLE
initial version of tracking category options manager

### PR DESCRIPTION
**Pull request by ddimmich**
Hi,

Would appreciate feedback about the approach - its not particularly consistent with the rest of the api but because adding options require that we submit a URL that has the parent TrackingCategoryID as part of it I ended up creating another 'manager' for it that is instantiated on a per trackingcategoryid basis.

Are there other 'sub' endpoints that need this type of approach?  If so, it may be better to make something more generic.  For now this works and at least I'm able to reasonably easily add options to TrackingCategories.

### CODE REVIEW

**Comment by ddimmich** [comment]
Forgot to add - see the updated Readme.md file for instructions on the new 'api' bits.

**Comment by aidanlister** [comment]
Thanks so much for working on this, I feel a bit uncomfortable with the xero.TCNAME syntax -- if the tracking category has a space in it or any other weird character it's not going to play nicely. Can we try something like xero.TrackingCategories['sdf']?

**Comment by obviattor1824** [comment]
Hi, I'm trying to put a new tracking category option, is this possible based on the above?

**Comment by ddimmich** [comment]
Yes - think so - although I think the main pyxero already has this with a cleaner implmentation.

**Comment by obviattor1824** [comment]
thanks, have been searching but not found any reference on it. 
I have a tracking category called "Yacht" and I want to add a new option called "new yachts", this is what I have, can you see something totally wrong with it? 
    xero.trackingcategories.put({'Name': 'Yacht', 'Options': {'Name': 'new yachts', 'Status': 'ACTIVE'}})

**Comment by obviattor1824** [comment]
```python
xero.trackingcategories.put({'Name': 'Yacht', 'Options': {'Name': 'new yachts', 'Status': 'ACTIVE'}})
```

**Comment by ddimmich** [comment]
Try new_yachts - as per the Aidan we might not support spaces in names.  
Otherwise looks about right.  Are you running the branch that supports 
this or the generic pyxero?

**Comment by obviattor1824** [comment]
Thanks, sorry for the hassle here, new_yachts didn't do it either. I just did pip install pyxero, how do I get the tracking options supported version (am a noobie, sorry)

**Comment by ddimmich** [comment]
You'd have to pip install the git version from my repository :

pip install git+https://github.com/tauri-tec/pyxero.git

That said - this version is a bit behind the main pyxero so if you need 
the latest version of that you'd need to merge the code for that.

**Pull request closed without merging**
