### PR TITLE
Add OAuth2 implementation

### PR DESCRIPTION
**Pull request by ollytheninja**
needs docs and testing

### CODE REVIEW

**Comment by TomskDiver** [comment]
@ollytheninja  how to use your fix? You may provide code example how connect to Xero with OAuth2?

**Comment by thornycrackers** [comment]
@ollytheninja I don't know if the API has been updated since this code was created but in my token response I was getting the key `expires_in` instead of `expires_at`

**Comment by ollytheninja** [comment]
@thornycrackers they are both returned but `expires_at` was easier to deal with, I probably wasn't thinking about publishing when I wrote that, I should really include everything for good measure

**Comment by ollytheninja** [comment]
@TomskDiver I'll get something written up soon! Just wanted to make it available as soon as possible

**Comment by ferdinandpolpol1** [comment]
@ollytheninja always getting a 

> CSRF Warning! State not equal in request and response.

    xero_flow = Flow(id, secret, scope, redirect_uri)

    if request.GET.get('code') and request.GET.get('state'):
        state = request.GET.get('state')
        code = request.GET.get('code')

        flow_complete = xero_flow.complete(state, code)
    else:
        url, state = xero_flow.start()
        return redirect(url)`

Am I using this right? Could you provide help or an example?

**Comment by thornycrackers** [comment]
@ferdinandpolpol1 You need to use the `state` that is returned in `xero_flow.start()` when you run `xero_flow.complete()` not the state that comes back in the request

**Comment by thornycrackers** [comment]
One issue I do keep having is when I complete the flow and get a token back I need to convert the `expires_at` key to a timestamp. 

```
token = flow.complete(state, url)
client = Client(CLIENT_ID, token.__dict__)
```
results in
```
File "/opt/venv/lib/python3.6/site-packages/xero/oauth2.py", line 70, in __init__
    creds = XeroOAuthV2(client_id=client_id, token=token)
  File "/opt/venv/lib/python3.6/site-packages/xero/oauth2.py", line 65, in __init__
    self.oauth = OAuth2(client_id=client_id, token=token)
  File "/opt/venv/lib/python3.6/site-packages/requests_oauthlib/oauth2_auth.py", line 20, in __init__
    self._client = client or WebApplicationClient(client_id, token=token)
  File "/opt/venv/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/web_application.py", line 37, in __init__
    super(WebApplicationClient, self).__init__(client_id, **kwargs)
  File "/opt/venv/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 118, in __init__
    self.populate_token_attributes(self.token)
  File "/opt/venv/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 493, in populate_token_attributes
    self._expires_at = int(response.get('expires_at'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.datetime'
```

but if I update it to a timestamp everything seems to be working:

```
token = flow.complete(state, url)
token.__dict__["expires_at"] = token.__dict__["expires_at"].timestamp()
client = Client(CLIENT_ID, token.__dict__)
```

**Comment by ferdinandpolpol1** [comment]
@thornycrackers Thanks! I found that the issue was that I was passing the code instead of the url.

**Comment by ollytheninja** [comment]
I just added to the readme, you can find my version here https://github.com/ollytheninja/pyxero/tree/oauth2#oauth2-applications

I think the issue with the expiry timestamp is that I call `token.as_json()`, dump it in the database (in this case a textfield in Django) and then retrieve it and create a client using `Client(Client(CLIENT_ID, json.loads(token))

I'll have to fix that because it's not intuitive at all!

**Comment by sdolemelipone** [comment]
Thanks @ollytheninja, this really saved my skin when one of my clients deleted their OAuth1.0 app by mistake. I have hacked together an implementation of refreshing tokens, it would be very useful to add that feature as well. I discovered that when calling `OAuth2Session.refresh_token()` it was necessary to pass in  `auth = requests.auth.HTTPBasicAuth(client_id, client_secret)`. `requests_oauthlib` does not do that automatically (as it does when calling `OAuth2Session.fetch_token()`).

**Comment by ollytheninja** [comment]
Weird! Would you like to pull request into my branch?
I was also thinking the other day I should write some tests for it

**Comment by sdolemelipone** [comment]
I've added a pull request to your repo with the changes I made to refresh tokens.
What you've done is really handy for getting this working, but I think we should probably write something more in the style of the existing `xero.auth.PublicCredentials` in xero.auth (which also handles the tenant_ids behind the scenes). I've created an alternative PR #277 so we can keep this one available for those that are using it already.

**Comment by sdolemelipone** [comment]
For anyone looking for an implementation similar to `auth.PublicCredentials` I have created PR #278.

**Comment by freakboy3742** [comment]
Thanks for the contribution! However, I think the implementation on #278 is a lot closer aligned to the architectural style of the rest of PyXero, and is a lot closer to being ready to merge. On that basis, I'm going to close this PR.

**Comment by ollytheninja** [comment]
No worries :smile:

**Comment by kcardona86** [comment]
Hi, I would like some help as I really have basic knowledge of python and I'm just trying to help my boss here. We had a script using pyxero which works flawlessly and she asked me if I can just replace the companies and download something else instead of Invoices, but I just discovered that Xero changed to OAuth 2, how can I go about it and what exactly should I do here? 

`# pip install pyxero pandas csvkit xlsxwriter
#https://github.com/freakboy3742/pyxero
import codecs
import datetime
import json


from time import sleep

# import pandas as pd
# from   pandas.io.json.normalize import nested_to_record
from xero import Xero
from xero.auth import PrivateCredentials

# TO CHANGE
#
# # Gaming Momentum Creds
# credentialsGM = PrivateCredentials(open('xero_login.txt', 'r').read().strip(),
#                                    open('xero_airflow.pem', 'r').read().strip())
#
#
# # Mobile Momentum Creds
# credentialsMM = PrivateCredentials(open('xero_login_MM.txt', 'r').read().strip(),
#                                    open('privatekey.pem', 'r').read().strip())

companies = ["LeoVegas Gaming plc", "Brands of Leo"]

# TO CHANGE
#
# xeroGM = Xero(credentialsGM)
# xeroMM = Xero(credentialsMM)


objs = [
    'journals',
    'manualjournals',
]


def default(o):
    if type(o) is datetime.date or type(o) is datetime.datetime:
        return o.isoformat()


def dump_json(obj='invoices'):
    for x in companies:
        all_ = []
        page = 1
        try:
            while True:
                print(x)
                print (obj, page)
                # TO CHANGE
                #
                # if x == "Mobile Momentum":
                #     resp = getattr(xeroMM, obj).filter(page=page) # WIP: sort?
                # elif x == "Gaming Momentum":
                #     resp = getattr(xeroGM, obj).filter(page=page)  # WIP: sort?
                sleep(1) # Rate limit
                if len(resp) < 1:
                    break

                all_ = all_ + resp
                page = page + 1
        except Exception as exc:

            print (obj, exc)

        for num, a in enumerate(all_):
            try:
                # TO REMOVE
                #
                # del a['Overpayments']  # WIP empty list not importing into BQ
            except:
                pass
            all_[num] = a

        with codecs.open(x+' '+obj + '.json', mode='w', encoding='utf-8') as f:
            for a in all_:
                 f.write(json.dumps(a, default=default))
                 f.write('\n')

for obj in objs:
    dump_json(obj)
`

Also what details should I enter in Xero App portal?
Screenshot 2020-04-24 at 4 51 42 PM

**Comment by ollytheninja** [comment]
@kcardona86 in future please start a new issue rather than using an existing closed one.

There is some information about using OAuth2 in the readme [here](https://github.com/freakboy3742/pyxero#using-oauth2-credentials)

With OAuth2 there is no Public and Private apps - all applications use the same authentication flow.
There are a few posts in [community.xero.com](https://community.xero.com), for example [this one](https://community.xero.com/developer/discussion/108428763) has some discussion on moving a private application to OAuth2.

> with oAuth 2.0 there is no longer the concept of private/public and partner apps. They all become one and the same. So the app would not require a private connection. If you are only going to use the app for private purposes you do the following.
> 
> 1. Make sure you request offline access
> 2. Use the oAuth Login Flow for the first time + select the organisation you want private access to. Potentially with some patience you could have the same user authenticate multiple organisations with the same token. The login flow needs to be repeated per org they want to add.
> 3. Save the token with Refresh Tokens.
> 4. If you have a token no longer show the Xero login but use the saved tokens/refresh token to continue.
> 5. Everytime your token expires just refresh it.
> 6. Prepare to handle a scenario where the user account that connected is no longer associated with the company in question. Say if this was an employee that they left the company - you will need to obtain a new token/login to proceed

Unfortunately you won't be able to easily migrate a locally running application like yours.
You may find the utility mentioned here https://community.xero.com/developer/discussion/109207632 useful.
They really didn't put too much thought into how the new OAuth2 implementation would function with apps that used private credentials before.

If you still have questions please open a new issue and @ me
Maybe you can help write some documentation to make it easier for others?

**Pull request closed without merging**
