### PR TITLE
An optional 'id' argument for Manager.save method.

### PR DESCRIPTION
**Pull request by vadim-pavlov**
The new argument should enable Xero API methods utilizing Resource ID URI parameter in POST requests. Such as deletion of payments and bank transactions:
https://developer.xero.com/documentation/api/payments#POST
https://developer.xero.com/documentation/api/banktransactions#POST

### CODE REVIEW

**Comment by vadim-pavlov** [comment]
I've changed the solution based on your feedback. I added a PaymentManager with a custom delete method.

**Comment by vadim-pavlov** [comment]
I guess a better alternative could be to pass a delete_strategy callable to the BaseManager constructor, in this case there will be no need to define a manager class for every entity that has non-standard API.

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Apologies for the delay in reviewing this; the PR appears to have drifted out of sync with main. Could I ask you to merge it with main?

**Comment by vadim-pavlov** [comment]
Not a problem @freakboy3742. I've merged it with the latest main.

**Comment by freakboy3742** [comment]
Looks like I have some additional housekeeping to do (dropping Python 3.6 support); I'll add that to my todo list, then review this for you.

**Review by freakboy3742 — APPROVED** [review]
Looks good; apologies again for the late review, and thanks for the contribution!

**Pull request merged**
