### PR TITLE
Support for Xero Payroll API

### PR DESCRIPTION
**Pull request by MattHealy**
I'm looking to pick up this library to replace the current PHP implementation I've got in production. I've made the changes in this pull request to support the Payroll functions I currently use, and written a sample client for updating a payslip, replicating the logic I currently have in production. The changes work well, from my testing.

I'm by no means an expert in Python, so I hope this PR doesn't violate any coding standards adhered to in this repo. Let me know if it needs changing.

Sample usage:

    payitems = xero.payrollAPI.payitems.all()
    payruns = xero.payrollAPI.payruns.filter(PayrollCalendarID = calendarid, PayRunStatus = 'Draft')
    payslip = xero.payrollAPI.payslip.save([{'PayslipID': payslipid, 'EmployeeID': employeeid, 'EarningsLines': earningslines}])

### CODE REVIEW

**Comment by MattHealy** [comment]
In relation to Issue #7

**Comment by aidanlister** [comment]
Hey Matt, this looks great! Would you be able to make a small change? My gut tells me that we should:

- rename Manager to BaseManager (and manager.py to basemanager.py)
- create a manager.py which simply extends BaseManager
- create a payrollmanager.py which extends BaseManager and sets the API endpoint in __init__ (rather than in a if/else)

Let me know if you want to have a crack at this?

**Comment by MattHealy** [comment]
Thanks Aidan, that makes sense to me and is definitely more elegant than the if/else. I'll get on to this.

**Comment by MattHealy** [comment]
Hey Aidan, I've refactored the manager classes as suggested.

**Comment by aidanlister** [comment]
Looks great! Good job on the refactor, and thanks for adding Payroll support it will be much appreciated by our users.

**Pull request merged**
