### PR TITLE
Better validation error

### PR DESCRIPTION
**Pull request by direvus**
Include details of validation errors in the main exception message, per #129

### CODE REVIEW

**Comment by aidanlister** [comment]
I'm not really sure what this is doing?

**Comment by direvus** [comment]
Please review discussion at #129 for full details, but currently the XeroBadRequest exception for validation errors ends up with a useless 'message' attribute.  This PR appends some detail of the validation problem in the main message, making it easier to troubleshoot validation problems.

Sorry for the noise in the commit history, that's due to some merges I made on the 'master' branch of my fork.

**Comment by aidanlister** [comment]
Can we go a little further and have something like: XeroAPIError: BadFormatting (invoice x had y, *and 5 other issues*)

**Comment by direvus** [comment]
We can't really do the "invoice x" part, because the Xero API doesn't give us that information.  See https://developer.xero.com/documentation/getting-started/http-response-codes/#title3

But I do think the "... and z other issues" bit has merit, I'll update my branch with that addition.

**Comment by direvus** [comment]
Thanks @aidanlister !

**Comment by jordanmkoncz** [comment]
Thanks for this @direvus! I was getting validation errors and running into the problem of the exception not providing any useful information; I've just updated to `0.9.0` and I'm now getting an exception that actually tells me what the problem is.

**Comment by direvus** [comment]
That's awesome @jordanmkoncz, thanks for the feedback!

**Pull request merged**
