### PR TITLE
Customisation for headers, query, and after-data-fetched action

### PR DESCRIPTION
**Pull request by aldian**

### CODE REVIEW

**Comment by aidanlister** [comment]
Could you explain what you're doing here?

**Comment by aldian** [comment]
Hi Aidan,

I apologise for the late answer.
The purpose of the code I added is to help me handle Xero API rate limit.
To handle rate limit, I need to know when the last API call was made. So I
need to record the time in a log.
To make the logging code cleaner I think it should be done inside an event
handling code, so it won't clobber with my app business logic.
So I added an event handling code to pyxero.

A pyxero user can add an on_data_fetched event like this:

xero = Xero(credentials, on_data_fetched=on_data_fetched)

That pyxero user can add log recording inside that on_data_fetched function.

That's it.


Regards,

Aldian Fazrihady

**Comment by aldian** [comment]
_get_results function in manager.py will exclude Organisation query result because it doesn't have 's' suffix in the text Organisation. I just added a trivial fix.

**Comment by freakboy3742** [comment]
Ok - this PR is now convolving at least three separate feature requests/bug reports.
 * Plural handling for Organization objects
 * Callbacks on API usage
 * Something to do with the includeArchive header value.

It's a lot easier to review and merge if you keep issues separate. 

In addition, each one of these issues needs to be tested. 

I'm going to close this PR; if you can open fresh PRs, one per problem, I'll evaluate them individually.

**Pull request closed without merging**
