### PR TITLE
Added Projects API methods

### PR DESCRIPTION
**Pull request by tkav**

### CODE REVIEW

**Comment by schinckel** [comment]
Hmm. Appears to be failing on Python 3.4

I'm not sure we want to be supporting that.

**Comment by tkav** [comment]
Any ideas why? I'll see if I can find the problem

**Comment by schinckel** [comment]
Looks like python-dateutil won't install for 3.4

**Comment by tkav** [comment]
Damn. Must be a separate issue. I didn't edit the requirements

**Comment by tkav** [comment]
Possibly related: https://github.com/dateutil/dateutil/pull/897

**Comment by sdolemelipone** [comment]
Looks like the error is caused by dateutil having version 0.0.0 after being installed. 
```
Running python-dateutil-2.8.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-y1ymqv0f/python-dateutil-2.8.1/egg-dist-tmp-g8qrc4h8
...
Adding python-dateutil 0.0.0 to easy-install.pth file
```

dateutil [2.8.1](https://github.com/dateutil/dateutil/releases/tag/2.8.1) was released on 3rd November so this is probably why our tests have been failing since then. In their release notes it appears the build process has been changed. I don't know enough to figure out what would have broken it.

As dateutil still supports Python3.4 I don't think the failures are a reason to drop support for it. 

Looking at https://github.com/pypa/setuptools_scm/issues/209 we might be able to fix this by installing the package from pip first in travis.yml. I will create a separate pull request to try this out.

**Comment by sdolemelipone** [comment]
PR #279 appears to fix the installation error.

**Pull request merged**
