### PR TITLE
add PKCE Oauth2 flow

### PR DESCRIPTION
**Pull request by rgammans**
I've finally gotten around to cleaning this up and adding some documentation, tests etc.

Fixes: #316

### CODE REVIEW

**Review by schinckel — CHANGES_REQUESTED** [review]
I don't know enough about the PCKE auth flow to say whether this is "the best way to do it", but it mostly looks okay.

There are a bunch of flake8/style fixes I'd like to see fixed - spaces, trailing commas and the like.

**Comment by rgammans** [comment]
I've updated it to lint cleanly with flake8.

As to whether it's the best approach, it's hard to say, but there are a good number of places a user can customise it if necessary. And it's easy to use in the simple cases.

But without knowing more use cases it's difficult to write documentation with advice for them.

**Comment by rgammans** [comment]
Hmm. I'll probably need to run isort, but master isn't clean against isort 5.10.1 either.

**Comment by rgammans** [comment]
Ah, I misspoke about isort cleanliness it turns out there are some config updates

**Review by freakboy3742 — APPROVED** [review]
Apologies for the delayed review; I've done a light review pass on the docs, but otherwise, seems reasonable to me. Thanks for the contribution!

**Pull request merged**
