### PR TITLE
429 error handling and tests #312

### PR DESCRIPTION
**Pull request by timrichardson**
for #312

### CODE REVIEW

**Comment by timrichardson** [comment]
PS closes #297

**Review by freakboy3742 — APPROVED** [review]
Looks good - thanks for the patch!

**Comment by SergeNasr** [comment]
Thanks a lot @timrichardson and @freakboy3742 !!

Would it be possible to cut a new release to to pull the fix into our codebase?

**Comment by freakboy3742** [comment]
@SergeNasr Done - v0.9.3 is up on PyPI.

**Pull request merged**
